// starters/react-parity/src/ParityContextualHelpFixture.jsx
import React from 'react';
import {ContextualHelp} from '@react-spectrum/contextualhelp';
import {Provider} from '@react-spectrum/provider';
import {theme as defaultTheme} from '@react-spectrum/theme-default';
import {Text} from '@react-spectrum/text';
import {Content, Footer} from '@react-spectrum/view';
import {Heading} from '@react-spectrum/text';

export function ParityContextualHelpFixture() {
  return (
    <Provider theme={defaultTheme} colorScheme="light" scale="medium" UNSAFE_className="fixture-root">
      <section data-parity-id="pkg-contextualhelp" className="fixture-card fixture-card--narrow">
        <ContextualHelp isOpen defaultOpen variant="info" isDismissable={false}>
          <Heading>Contextual help parity</Heading>
          <Content>Contextual help package visual baseline</Content>
          <Footer>
            <Text>Footer slot content</Text>
          </Footer>
        </ContextualHelp>
      </section>
    </Provider>
  );
}

// starters/vue/src/ParityContextualHelpFixture.vue
<template>
  <Provider color-scheme="light" scale="medium" class="fixture-root">
    <ContextualHelp :model-value="true" variant="info" title="Contextual help parity" :dismissable="false">
      Contextual help package visual baseline
      <template #footer>
        <Text variant="detail">Footer slot content</Text>
      </template>
    </ContextualHelp>
  </Provider>
</template>

<script setup lang="ts">
import {ContextualHelp} from '@vue-spectrum/contextualhelp';
import {Provider} from '@vue-spectrum/provider';
import {Text} from '@vue-spectrum/text';
</script>

<style scoped>
.fixture-root {
  min-height: 100vh;
  background: #f5f5f5;
  padding: 24px;
}
</style>
