// starters/react-parity/src/ParityDialogFixture.jsx
import React from 'react';
import {Button} from '@react-spectrum/button';
import {Dialog, DialogTrigger} from '@react-spectrum/dialog';
import {Provider} from '@react-spectrum/provider';
import {theme as defaultTheme} from '@react-spectrum/theme-default';
import {Content} from '@react-spectrum/view';
import {Heading} from '@react-spectrum/text';

export function ParityDialogFixture() {
  return (
    <Provider theme={defaultTheme} colorScheme="light" scale="medium" UNSAFE_className="fixture-root">
      <section data-parity-id="pkg-dialog" className="fixture-card fixture-card--narrow">
        <DialogTrigger type="modal" isOpen defaultOpen>
          <Button variant="secondary">Open dialog</Button>
          <Dialog>
            <Heading>Dialog parity fixture</Heading>
            <Content>Dialog package visual baseline</Content>
          </Dialog>
        </DialogTrigger>
      </section>
    </Provider>
  );
}

// starters/vue/src/ParityDialogFixture.vue
<template>
  <Provider color-scheme="light" scale="medium" class="fixture-root">
    <Dialog :open="true" title="Dialog parity fixture" :dismissable="false">
      <p>Dialog package visual baseline</p>
    </Dialog>
  </Provider>
</template>

<script setup lang="ts">
import {Dialog} from '@vue-spectrum/dialog';
import {Provider} from '@vue-spectrum/provider';
</script>

<style scoped>
.fixture-root {
  min-height: 100vh;
  background: #f5f5f5;
}
</style>
