// starters/react-parity/src/ParityOverlayPlacementFixture.jsx
import React from 'react';
import {Button} from '@react-spectrum/button';
import {Provider} from '@react-spectrum/provider';
import {theme as defaultTheme} from '@react-spectrum/theme-default';
import {Text} from '@react-spectrum/text';
import {Tooltip, TooltipTrigger} from '@react-spectrum/tooltip';

export function ParityOverlayPlacementFixture() {
  return (
    <Provider theme={defaultTheme} colorScheme="light" scale="medium" UNSAFE_className="fixture-root">
      <section data-parity-id="overlay-placement-matrix" className="fixture-card fixture-card--overlay">
        <Text>Overlay Placement Matrix</Text>
        <div className="placement-grid">
          <TooltipTrigger isOpen placement="top">
            <Button variant="secondary">Top</Button>
            <Tooltip>Top placement</Tooltip>
          </TooltipTrigger>
          <TooltipTrigger isOpen placement="right">
            <Button variant="secondary">Right</Button>
            <Tooltip>Right placement</Tooltip>
          </TooltipTrigger>
          <TooltipTrigger isOpen placement="bottom">
            <Button variant="secondary">Bottom</Button>
            <Tooltip>Bottom placement</Tooltip>
          </TooltipTrigger>
          <TooltipTrigger isOpen placement="left">
            <Button variant="secondary">Left</Button>
            <Tooltip>Left placement</Tooltip>
          </TooltipTrigger>
        </div>
      </section>
    </Provider>
  );
}

// starters/vue/src/ParityOverlayPlacementFixture.vue
<template>
  <Provider color-scheme="light" scale="medium" class="fixture-root">
    <section data-parity-id="overlay-placement-matrix" class="fixture-card">
      <Text variant="heading">Overlay Placement Matrix</Text>
      <div class="placement-grid">
        <TooltipTrigger :model-value="true" content="Top placement" placement="top">
          <Button variant="secondary">Top</Button>
        </TooltipTrigger>
        <TooltipTrigger :model-value="true" content="Right placement" placement="right">
          <Button variant="secondary">Right</Button>
        </TooltipTrigger>
        <TooltipTrigger :model-value="true" content="Bottom placement" placement="bottom">
          <Button variant="secondary">Bottom</Button>
        </TooltipTrigger>
        <TooltipTrigger :model-value="true" content="Left placement" placement="left">
          <Button variant="secondary">Left</Button>
        </TooltipTrigger>
      </div>
    </section>
  </Provider>
</template>

<script setup lang="ts">
import {Button} from '@vue-spectrum/button';
import {Provider} from '@vue-spectrum/provider';
import {Text} from '@vue-spectrum/text';
import {TooltipTrigger} from '@vue-spectrum/tooltip';
</script>

<style scoped>
.fixture-root {
  min-height: 100vh;
  background: #f5f5f5;
  padding: 24px;
}

.fixture-card {
  align-items: stretch;
  background: #ffffff;
  border: 1px solid #d8d8d8;
  border-radius: 8px;
  display: grid;
  gap: 16px;
  margin: 0 auto;
  max-width: 720px;
  padding: 20px;
}

.placement-grid {
  display: grid;
  gap: 24px;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  justify-items: center;
  min-height: 220px;
  padding: 16px;
}
</style>
