// starters/vue/src/ParityRtlFixture.vue
<template>
  <Provider dir="rtl" locale="ar-EG" color-scheme="light" scale="medium" class="fixture-root">
    <section data-parity-id="rtl-cluster" class="fixture-card">
      <Text variant="heading">واجهة RTL</Text>
      <ButtonGroup>
        <Button variant="primary">حفظ</Button>
        <Button variant="secondary">إلغاء</Button>
      </ButtonGroup>
      <TextField label="المالك" model-value="أفري" />
      <Tabs v-model="selectedTab" :items="tabs" aria-label="علامات التبويب" />
      <Table :columns="columns" :rows="rows" row-key="ticket" caption="تذاكر" />
    </section>
  </Provider>
</template>

<script setup lang="ts">
import {ref} from 'vue';
import {Button} from '@vue-spectrum/button';
import {ButtonGroup} from '@vue-spectrum/buttongroup';
import {Provider} from '@vue-spectrum/provider';
import {Table} from '@vue-spectrum/table';
import {Tabs, type TabItemData} from '@vue-spectrum/tabs';
import {Text} from '@vue-spectrum/text';
import {TextField} from '@vue-spectrum/textfield';

const selectedTab = ref('overview');

const tabs: TabItemData[] = [
  {key: 'overview', label: 'نظرة عامة', content: 'محتوى النظرة العامة'},
  {key: 'details', label: 'تفاصيل', content: 'محتوى التفاصيل'}
];

const columns = [
  {key: 'ticket', label: 'التذكرة'},
  {key: 'owner', label: 'المالك'}
];

const rows = [
  {ticket: 'T-100', owner: 'أفري'},
  {ticket: 'T-101', owner: 'كوين'}
];
</script>

<style scoped>
.fixture-root {
  min-height: 100vh;
  background: #f5f5f5;
  padding: 24px;
}

.fixture-card {
  align-items: stretch;
  background: #ffffff;
  border: 1px solid #d8d8d8;
  border-radius: 8px;
  display: grid;
  gap: 12px;
  margin: 0 auto;
  max-width: 960px;
  padding: 16px;
}
</style>

// starters/react-parity/src/ParityRtlFixture.jsx
import React from 'react';
import {Button} from '@react-spectrum/button';
import {ButtonGroup} from '@react-spectrum/buttongroup';
import {Provider} from '@react-spectrum/provider';
import {theme as defaultTheme} from '@react-spectrum/theme-default';
import {Cell, Column, Row, TableBody, TableHeader, TableView} from '@react-spectrum/table';
import {Tabs} from '@react-spectrum/tabs';
import {Text} from '@react-spectrum/text';
import {TextField} from '@react-spectrum/textfield';
import {Item} from '@react-stately/collections';

export function ParityRtlFixture() {
  return (
    <Provider theme={defaultTheme} locale="ar-EG" colorScheme="light" scale="medium" UNSAFE_className="fixture-root">
      <section data-parity-id="rtl-cluster" className="fixture-card">
        <Text>واجهة RTL</Text>
        <ButtonGroup>
          <Button variant="cta">حفظ</Button>
          <Button variant="secondary">إلغاء</Button>
        </ButtonGroup>
        <TextField label="المالك" defaultValue="أفري" />
        <Tabs aria-label="علامات التبويب" defaultSelectedKey="overview">
          <Item key="overview" title="نظرة عامة">محتوى النظرة العامة</Item>
          <Item key="details" title="تفاصيل">محتوى التفاصيل</Item>
        </Tabs>
        <TableView aria-label="تذاكر" selectionMode="single" defaultSelectedKeys={['T-100']}>
          <TableHeader>
            <Column key="ticket">التذكرة</Column>
            <Column key="owner">المالك</Column>
          </TableHeader>
          <TableBody>
            <Row key="T-100"><Cell>T-100</Cell><Cell>أفري</Cell></Row>
            <Row key="T-101"><Cell>T-101</Cell><Cell>كوين</Cell></Row>
          </TableBody>
        </TableView>
      </section>
    </Provider>
  );
}
